### ISSUE TITLE
对于数据集的问题

### ISSUE THREAD

**Issue by wanghaorananda** [hanna-xu/DDcGAN#7]
作者您好，我想知道您的训练数据是否都是单通道的灰度图像？
对于我目前的工作，我想使用RGB的图像来进行训练是否可行？
                         感激不尽

**Comment by hanna-xu** [comment]
对，现在的训练集是单通道的，对于RGB图像，需要根据您的工作修改相关的网络设置和损失函数


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hanna-xu/DDcGAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 下午3:28
收件人:&nbsp;"hanna-xu/DDcGAN"<DDcGAN@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hanna-xu/DDcGAN] 对于数据集的问题 (#7)





 
作者您好，我想知道您的训练数据是否都是单通道的灰度图像？
 对于我目前的工作，我想使用RGB的图像来进行训练是否可行？
 感激不尽
